services:
  douyin-downloader:
    image: evil0ctal/douyin_tiktok_download_api:latest
    container_name: douyin_downloader
    ports:
      - "80:80"
    volumes:
      - ./douyin_downloader:/app/douyin_downloader
      - ./douyin_downloader/data:/data
    networks:
      - douyin_api

  api:
    build: ./api
    container_name: api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app/api
    networks:
      - douyin_api
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - WATCHFILES_FORCE_POLLING=true

networks:
  douyin_api:
    driver: bridge