services:
  douyin-downloader:
    image: evil0ctal/douyin_tiktok_download_api:latest
    container_name: douyin_downloader
    ports:
      - "80:80"
    volumes:
      - ./douyin_downloader:/app/douyin_downloader
      - ./douyin_downloader/data:/data
      - ./douyin_downloader/config/config.yaml:/app/crawlers/douyin/web/config.yaml
    networks:
      - douyin_api

  api:
    build: ./api
    container_name: api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app/api
      - ./douyin_downloader/config/config.yaml:/app/crawlers/douyin/web/config.yaml
    networks:
      - douyin_api
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - WATCHFILES_FORCE_POLLING=true


  video_tools:
    build: ./video_tools
    container_name: video_tools
    ports:
      - "9000:9000"
    volumes:
      - ./video_tools:/app/video_tools
    networks:
      - douyin_api
    command: uvicorn src.main:app --host 0.0.0.0 --port 9000 --reload
    environment:
      - WATCHFILES_FORCE_POLLING=true

networks:
  douyin_api:
    driver: bridge